// AUTO-GENERATED by scripts/migrate-json-to-ts.ts — не редактировать вручную.
// Источник: data/catechism.json. Форма — docs/contracts/content-data-contract.md §2.

export const QUESTION_VERSES = [
  {
    "question_id": 1,
    "verse_id": 1,
    "position": 1
  },
  {
    "question_id": 2,
    "verse_id": 2,
    "position": 1
  },
  {
    "question_id": 3,
    "verse_id": 3,
    "position": 1
  },
  {
    "question_id": 4,
    "verse_id": 4,
    "position": 1
  },
  {
    "question_id": 5,
    "verse_id": 5,
    "position": 1
  },
  {
    "question_id": 6,
    "verse_id": 6,
    "position": 1
  },
  {
    "question_id": 7,
    "verse_id": 7,
    "position": 1
  },
  {
    "question_id": 8,
    "verse_id": 8,
    "position": 1
  },
  {
    "question_id": 9,
    "verse_id": 9,
    "position": 1
  },
  {
    "question_id": 10,
    "verse_id": 10,
    "position": 1
  },
  {
    "question_id": 11,
    "verse_id": 11,
    "position": 1
  },
  {
    "question_id": 12,
    "verse_id": 12,
    "position": 1
  },
  {
    "question_id": 13,
    "verse_id": 13,
    "position": 1
  },
  {
    "question_id": 14,
    "verse_id": 14,
    "position": 1
  },
  {
    "question_id": 15,
    "verse_id": 8,
    "position": 1
  },
  {
    "question_id": 16,
    "verse_id": 15,
    "position": 1
  },
  {
    "question_id": 17,
    "verse_id": 16,
    "position": 1
  },
  {
    "question_id": 18,
    "verse_id": 16,
    "position": 1
  },
  {
    "question_id": 19,
    "verse_id": 3,
    "position": 1
  },
  {
    "question_id": 20,
    "verse_id": 17,
    "position": 1
  },
  {
    "question_id": 21,
    "verse_id": 18,
    "position": 1
  },
  {
    "question_id": 22,
    "verse_id": 19,
    "position": 1
  },
  {
    "question_id": 23,
    "verse_id": 20,
    "position": 1
  },
  {
    "question_id": 24,
    "verse_id": 21,
    "position": 1
  },
  {
    "question_id": 25,
    "verse_id": 22,
    "position": 1
  },
  {
    "question_id": 26,
    "verse_id": 23,
    "position": 1
  },
  {
    "question_id": 27,
    "verse_id": 24,
    "position": 1
  },
  {
    "question_id": 28,
    "verse_id": 23,
    "position": 1
  },
  {
    "question_id": 29,
    "verse_id": 25,
    "position": 1
  },
  {
    "question_id": 30,
    "verse_id": 26,
    "position": 1
  },
  {
    "question_id": 31,
    "verse_id": 3,
    "position": 1
  },
  {
    "question_id": 32,
    "verse_id": 27,
    "position": 1
  },
  {
    "question_id": 33,
    "verse_id": 28,
    "position": 1
  },
  {
    "question_id": 34,
    "verse_id": 29,
    "position": 1
  },
  {
    "question_id": 35,
    "verse_id": 30,
    "position": 1
  },
  {
    "question_id": 36,
    "verse_id": 31,
    "position": 1
  },
  {
    "question_id": 37,
    "verse_id": 32,
    "position": 1
  },
  {
    "question_id": 38,
    "verse_id": 33,
    "position": 1
  },
  {
    "question_id": 39,
    "verse_id": 34,
    "position": 1
  },
  {
    "question_id": 40,
    "verse_id": 35,
    "position": 1
  },
  {
    "question_id": 41,
    "verse_id": 36,
    "position": 1
  },
  {
    "question_id": 42,
    "verse_id": 37,
    "position": 1
  },
  {
    "question_id": 43,
    "verse_id": 38,
    "position": 1
  },
  {
    "question_id": 44,
    "verse_id": 39,
    "position": 1
  },
  {
    "question_id": 45,
    "verse_id": 40,
    "position": 1
  },
  {
    "question_id": 46,
    "verse_id": 41,
    "position": 1
  },
  {
    "question_id": 47,
    "verse_id": 42,
    "position": 1
  },
  {
    "question_id": 48,
    "verse_id": 43,
    "position": 1
  },
  {
    "question_id": 49,
    "verse_id": 44,
    "position": 1
  },
  {
    "question_id": 50,
    "verse_id": 45,
    "position": 1
  },
  {
    "question_id": 51,
    "verse_id": 46,
    "position": 1
  },
  {
    "question_id": 52,
    "verse_id": 47,
    "position": 1
  },
  {
    "question_id": 53,
    "verse_id": 48,
    "position": 1
  },
  {
    "question_id": 54,
    "verse_id": 49,
    "position": 1
  },
  {
    "question_id": 55,
    "verse_id": 50,
    "position": 1
  },
  {
    "question_id": 56,
    "verse_id": 51,
    "position": 1
  },
  {
    "question_id": 57,
    "verse_id": 52,
    "position": 1
  },
  {
    "question_id": 58,
    "verse_id": 53,
    "position": 1
  },
  {
    "question_id": 58,
    "verse_id": 54,
    "position": 2
  },
  {
    "question_id": 58,
    "verse_id": 55,
    "position": 3
  },
  {
    "question_id": 59,
    "verse_id": 56,
    "position": 1
  },
  {
    "question_id": 60,
    "verse_id": 57,
    "position": 1
  },
  {
    "question_id": 61,
    "verse_id": 58,
    "position": 1
  },
  {
    "question_id": 62,
    "verse_id": 59,
    "position": 1
  },
  {
    "question_id": 63,
    "verse_id": 60,
    "position": 1
  },
  {
    "question_id": 64,
    "verse_id": 61,
    "position": 1
  },
  {
    "question_id": 65,
    "verse_id": 62,
    "position": 1
  },
  {
    "question_id": 66,
    "verse_id": 63,
    "position": 1
  },
  {
    "question_id": 68,
    "verse_id": 64,
    "position": 1
  },
  {
    "question_id": 70,
    "verse_id": 65,
    "position": 1
  },
  {
    "question_id": 72,
    "verse_id": 66,
    "position": 1
  },
  {
    "question_id": 74,
    "verse_id": 67,
    "position": 1
  },
  {
    "question_id": 75,
    "verse_id": 68,
    "position": 1
  },
  {
    "question_id": 75,
    "verse_id": 69,
    "position": 2
  },
  {
    "question_id": 76,
    "verse_id": 70,
    "position": 1
  },
  {
    "question_id": 78,
    "verse_id": 71,
    "position": 1
  },
  {
    "question_id": 80,
    "verse_id": 72,
    "position": 1
  },
  {
    "question_id": 80,
    "verse_id": 73,
    "position": 2
  },
  {
    "question_id": 82,
    "verse_id": 74,
    "position": 1
  },
  {
    "question_id": 84,
    "verse_id": 75,
    "position": 1
  },
  {
    "question_id": 86,
    "verse_id": 76,
    "position": 1
  },
  {
    "question_id": 88,
    "verse_id": 77,
    "position": 1
  },
  {
    "question_id": 89,
    "verse_id": 78,
    "position": 1
  },
  {
    "question_id": 90,
    "verse_id": 44,
    "position": 1
  },
  {
    "question_id": 90,
    "verse_id": 79,
    "position": 2
  },
  {
    "question_id": 91,
    "verse_id": 80,
    "position": 1
  },
  {
    "question_id": 91,
    "verse_id": 81,
    "position": 2
  },
  {
    "question_id": 92,
    "verse_id": 82,
    "position": 1
  },
  {
    "question_id": 93,
    "verse_id": 38,
    "position": 1
  },
  {
    "question_id": 94,
    "verse_id": 83,
    "position": 1
  },
  {
    "question_id": 95,
    "verse_id": 84,
    "position": 1
  },
  {
    "question_id": 95,
    "verse_id": 85,
    "position": 2
  },
  {
    "question_id": 96,
    "verse_id": 6,
    "position": 1
  },
  {
    "question_id": 97,
    "verse_id": 86,
    "position": 1
  },
  {
    "question_id": 98,
    "verse_id": 87,
    "position": 1
  },
  {
    "question_id": 99,
    "verse_id": 88,
    "position": 1
  },
  {
    "question_id": 100,
    "verse_id": 89,
    "position": 1
  },
  {
    "question_id": 101,
    "verse_id": 90,
    "position": 1
  },
  {
    "question_id": 102,
    "verse_id": 91,
    "position": 1
  },
  {
    "question_id": 103,
    "verse_id": 92,
    "position": 1
  },
  {
    "question_id": 104,
    "verse_id": 93,
    "position": 1
  },
  {
    "question_id": 106,
    "verse_id": 94,
    "position": 1
  },
  {
    "question_id": 107,
    "verse_id": 95,
    "position": 1
  },
  {
    "question_id": 108,
    "verse_id": 96,
    "position": 1
  },
  {
    "question_id": 109,
    "verse_id": 97,
    "position": 1
  },
  {
    "question_id": 110,
    "verse_id": 98,
    "position": 1
  },
  {
    "question_id": 111,
    "verse_id": 99,
    "position": 1
  },
  {
    "question_id": 112,
    "verse_id": 100,
    "position": 1
  },
  {
    "question_id": 113,
    "verse_id": 101,
    "position": 1
  },
  {
    "question_id": 114,
    "verse_id": 102,
    "position": 1
  }
] as const;
