// AUTO-GENERATED by scripts/migrate-json-to-ts.ts — не редактировать вручную.
// Источник: data/catechism.json. Форма — docs/contracts/content-data-contract.md §2.

export const TOPICS = [
  {
    "topic_id": 1,
    "topic_name": "Бог"
  },
  {
    "topic_id": 2,
    "topic_name": "Сотворение"
  },
  {
    "topic_id": 3,
    "topic_name": "Как человек согрешил?"
  },
  {
    "topic_id": 4,
    "topic_name": "Что произошло в результате греха?"
  },
  {
    "topic_id": 5,
    "topic_name": "Спасение"
  },
  {
    "topic_id": 6,
    "topic_name": "Иисус Христос – Пророк, Священник и Царь"
  },
  {
    "topic_id": 7,
    "topic_name": "Десять заповедей"
  },
  {
    "topic_id": 8,
    "topic_name": "Соблюдение Божьих законов"
  },
  {
    "topic_id": 9,
    "topic_name": "Способ спасения"
  },
  {
    "topic_id": 10,
    "topic_name": "Жизнь спасенного человека"
  },
  {
    "topic_id": 11,
    "topic_name": "Крещение и вечеря Господня"
  },
  {
    "topic_id": 12,
    "topic_name": "Молитва"
  },
  {
    "topic_id": 13,
    "topic_name": "Где Иисус Христос находится сейчас?"
  },
  {
    "topic_id": 14,
    "topic_name": "Смерть"
  },
  {
    "topic_id": 15,
    "topic_name": "Ад"
  },
  {
    "topic_id": 16,
    "topic_name": "Рай"
  }
] as const;
