// Разовый скрипт миграции data/catechism.json -> content/*.ts (Фаза 9.1).
// Не часть рантайма приложения.
//
// Задача 9.1.1: чтение data/catechism.json и валидация через CatechismSchema
// из utils/catechism.ts (та же superRefine-проверка ссылочной целостности,
// что и сейчас) — обязательный первый шаг перед генерацией content/*.ts.
//
// Задача 9.1.2: сериализация уже провалидированных данных в
// content/topics.ts, content/questions.ts, content/verses.ts,
// content/question-verses.ts (форма — docs/contracts/content-data-contract.md
// §2), с явной проверкой счётчиков (§3) после генерации.
//
// Запуск: npx tsx scripts/migrate-json-to-ts.ts

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT_DIR = path.join(REPO_ROOT, 'content');

/** Ожидаемые счётчики по docs/contracts/content-data-contract.md §3. */
const EXPECTED_COUNTS = {
  topics: 16,
  questions: 114,
  verses: 102,
  question_verses: 110,
} as const;

/** Сериализует массив в TS-модуль вида `export const NAME = [...] as const;`. */
function renderContentModule(exportName: string, items: readonly unknown[]): string {
  const body = JSON.stringify(items, null, 2);
  return (
    `// AUTO-GENERATED by scripts/migrate-json-to-ts.ts — не редактировать вручную.\n` +
    `// Источник: data/catechism.json. Форма — docs/contracts/content-data-contract.md §2.\n\n` +
    `export const ${exportName} = ${body} as const;\n`
  );
}

/** Импорт CatechismSchema/данных из utils/catechism.ts. Модуль сам читает
 *  data/catechism.json и вызывает CatechismSchema.parse() при загрузке —
 *  ошибки чтения/валидации всплывают как rejection этого импорта. */
async function loadValidatedCatechism() {
  try {
    return await import('../utils/catechism.ts');
  } catch (err) {
    throw err instanceof Error
      ? err
      : new Error(`Не удалось загрузить/провалидировать data/catechism.json: ${String(err)}`);
  }
}

async function main(): Promise<void> {
  const { catechism } = await loadValidatedCatechism();

  console.log('data/catechism.json валиден (CatechismSchema.parse прошёл без ошибок):');
  console.log(`  topics: ${catechism.topics.length}`);
  console.log(`  questions: ${catechism.questions.length}`);
  console.log(`  verses: ${catechism.verses.length}`);
  console.log(`  question_verses: ${catechism.question_verses.length}`);

  // Явная проверка счётчиков после валидации Zod — на случай расхождения
  // между схемой (которая не фиксирует точные count) и контрактом.
  const actualCounts = {
    topics: catechism.topics.length,
    questions: catechism.questions.length,
    verses: catechism.verses.length,
    question_verses: catechism.question_verses.length,
  } as const;

  const mismatches = (Object.keys(EXPECTED_COUNTS) as (keyof typeof EXPECTED_COUNTS)[]).filter(
    (key) => actualCounts[key] !== EXPECTED_COUNTS[key],
  );
  if (mismatches.length > 0) {
    throw new Error(
      `Несовпадение счётчиков с content-data-contract.md §3: ${mismatches
        .map((key) => `${key} ожидалось ${EXPECTED_COUNTS[key]}, получено ${actualCounts[key]}`)
        .join('; ')}`,
    );
  }

  const files: { path: string; exportName: string; items: readonly unknown[] }[] = [
    { path: path.join(CONTENT_DIR, 'topics.ts'), exportName: 'TOPICS', items: catechism.topics },
    {
      path: path.join(CONTENT_DIR, 'questions.ts'),
      exportName: 'QUESTIONS',
      items: catechism.questions,
    },
    { path: path.join(CONTENT_DIR, 'verses.ts'), exportName: 'VERSES', items: catechism.verses },
    {
      path: path.join(CONTENT_DIR, 'question-verses.ts'),
      exportName: 'QUESTION_VERSES',
      items: catechism.question_verses,
    },
  ];

  await mkdir(CONTENT_DIR, { recursive: true });
  for (const file of files) {
    await writeFile(file.path, renderContentModule(file.exportName, file.items), 'utf-8');
  }

  console.log('\nСгенерированы файлы:');
  for (const file of files) {
    console.log(`  ${path.relative(REPO_ROOT, file.path)} (${file.exportName}: ${file.items.length})`);
  }
}

main().catch((err: unknown) => {
  if (err instanceof z.ZodError) {
    console.error('Валидация data/catechism.json провалена:');
    for (const issue of err.issues) {
      console.error(`  - [${issue.path.join('.') || '(root)'}] ${issue.message}`);
    }
  } else {
    console.error(err instanceof Error ? err.message : String(err));
  }
  process.exit(1);
});
